# Specify directory where to install Homebrew apps
cask_args appdir: "/Applications"

brew analytics off

tap "drud/ddev"
tap "homebrew/aliases"
tap "homebrew/bundle"
tap "homebrew/services"
tap "instrumenta/instrumenta"
tap "isen-ng/dotnet-sdk-versions"
tap "mutagen-io/mutagen"

#### BREWS
brew "git"
brew "git-flow"
brew "helm"
brew "htop"
brew "jq"
brew "kubernetes-cli"
brew "kubectx"
brew "m-cli"
brew "make"
brew "mas"
brew "siege"
brew "swaks"
brew "telnet"
brew "terminal-notifier"
brew "terraform"
brew "terragrunt"
brew "tfsec"
brew "tmux"
brew "vcpkg"
brew "watchman"
brew "wget"
brew "zsh"
brew "drud/ddev/ddev"
brew "mise"

#### CASKS
cask "alfred"
cask "beekeeper-studio"
cask "beyond-compare"
cask "blockblock"
cask "caffeine"
cask "clockify"
cask "enpass"
cask "firefox"
cask "flycut"
cask "font-fira-code"
cask "iterm2"
cask "keka"
cask "kekaexternalhelper"
cask "knockknock"
cask "lulu"
cask "macdown"
cask "microsoft-edge"
cask "microsoft-outlook"
cask "monitorcontrol"
cask "ngrok"
cask "openkey"
cask "oversight"
cask "phpstorm"
cask "postman"
cask "qlimagesize"
cask "rectangle"
cask "rider"
cask "shottr"
cask "skype"
cask "slack"
cask "spotify"
cask "sublime-text"
cask "visual-studio-code"
cask "whatsapp"
cask "zalo"
cask "alt-tab"
cask "google-chrome"
cask "mongodb-compass"
cask "jordanbaird-ice"
cask "mountain-duck"
cask "drawio"
cask "craft"
cask "pritunl"


#### MAS
mas 'Xcode', id: 497799835
